/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bennofs.gradle.continuous;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

import javax.annotation.Nonnull;

/**
 *  Gradle plugin that provides the {@link ContinuousJavaExec} task.
 *  The plugin itself doesn't alter the project, but this class is required for a valid gradle plugin.
 */
@SuppressWarnings("UnstableApiUsage")
public class ContinuousExecPlugin implements Plugin<Project> {
    public void apply(@Nonnull Project project) {
    }
}
