/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.bennofs.gradle.continuous;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'io.github.bennofs.gradle.continuous-exec' plugin.
 */
public class GradleContinuousExecPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.github.bennofs.continuous-exec");
    }
}
